=== JuanEladio04/LenguajesDeMarcas-DAW/BloqueDTD/Examen/ViajesPosiblesaRealizar.dtd
<!ELEMENT Viaje (Avion+, Barco?, Playa?, Piscina+, Fiesta*, OtroPais)>

<!ELEMENT Avion (#PCDATA)>
<!ELEMENT Playa (Piedras | Arena)*>
<!ELEMENT Piedras EMPTY>
<!ELEMENT Arena EMPTY>

<!ELEMENT Piscina (Niños?, Adultos*, (Socorrista | Vigia))*>
<!ELEMENT Niños EMPTY>
<!ELEMENT Adultos (#PCDATA)>
<!ATTLIST Adultos rescatadoPor IDREF #IMPLIED
                    nombre ID #REQUIRED>
<!ELEMENT Socorrista (#PCDATA)>
<!ATTLIST Socorrista nombre  ID #FIXED "Paco"
                    amigoDe IDREF #REQUIRED>

<!ELEMENT Fiesta (Borracho*, Camareros+)>
<!ELEMENT Borracho EMPTY>
<!ELEMENT Camareros (#PCDATA)>
<!ENTITY % Tipo "Tipo ID #REQUIRED
                CoctelesBebidos NMTOKEN #IMPLIED
                Fumador (si | no) 'no'
                colorCamisa CDATA #IMPLIED">
<!ATTLIST Borracho %Tipo;>
<!ATTLIST Camareros %Tipo;>

<!ELEMENT OtroPais (Mexico?, Japon?, USA?)>
<!ENTITY % caracteristicas "nombre ID #REQUIRED
                            color (rojo | amarillo | azul) 'azul'
                            Tusrista  IDREFS #IMPLIED">
<!ELEMENT Mexico (#PCDATA)>
<!ATTLIST Mexico %caracteristicas;>
<!ELEMENT Japon EMPTY>
<!ATTLIST Japon %caracteristicas;>
<!ELEMENT USA (#PCDATA)>
<!ATTLIST USA %caracteristicas;>

=== JuanEladio04/LenguajesDeMarcas-DAW/BloqueDTD/Examen/ViajesPosiblesaRealizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Viaje SYSTEM "ViajesPosiblesaRealizar.dtd">

<Viaje>
    <Avion>
        Vuelo Internacional
    </Avion>
    <Playa>
        <Arena/>
    </Playa>
    <Piscina>
        <Adultos nombre = "Carmen">
            Jovenes
        </Adultos>
        <Adultos nombre = "Antonio" rescatadoPor="Paco">
            Casi se ahoga y ahora es amigo de Paco
        </Adultos>

        <Socorrista nombre="Paco" amigoDe="Antonio">
            Ahora, amigo de Antonio
        </Socorrista>
    </Piscina>
    <Fiesta>
        <Borracho Tipo="BuscaPeleas" Fumador="si"/>
        <Camareros Tipo="BuenaGente" CoctelesBebidos="3" Fumador="no">
            Servicial
        </Camareros>
    </Fiesta>
    <OtroPais>
        <Japon nombre="jpn" color="rojo"/>
        <USA nombre="USA" color="azul" Tusrista="Paco Antonio">
            NEW YORK
        </USA>
    </OtroPais>
</Viaje>
