=== JuanEladio04/LenguajesDeMarcas-DAW/BloqueDTD/ExamenesRepaso/Minecraft.dtd
<!ELEMENT Minecraft (UnJugador+, DosJugadores?)>
<!ELEMENT UnJugador (Mundo?)>
<!ELEMENT Mundo (Bloque* , ( Agua+ | Lava?))>
<!ELEMENT Bloque (#PCDATA | Flotante | Mineral)*>
<!ELEMENT Flotante EMPTY>
<!ELEMENT Mineral (#PCDATA)>
<!ELEMENT Agua (Peces?)>

<!ELEMENT DosJugadores (Multijugador+)>
<!ELEMENT Multijugador EMPTY>

<!ENTITY % caracteristicas "destruible (si | no) 'si'
                            nombre ID #REQUIRED
                            pertecece IDREF #IMPLIED">

<!ATTLIST Bloque %caracteristicas;>
<!ATTLIST Agua %caracteristicas;>
<!ATTLIST Mineral %caracteristicas;>

<!ATTLIST Minecraft creador CDATA #FIXED "Notch">

=== JuanEladio04/LenguajesDeMarcas-DAW/BloqueDTD/ExamenesRepaso/Minecraft.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Minecraft SYSTEM "Minecraft.dtd">

<Minecraft creador="Notch">
    <UnJugador>
        <Mundo>
            <Bloque destruible="si" nombre="cesped">
                Cuadrado
            </Bloque>
            <Bloque destruible="no" nombre="nube">
                <Flotante/>
            </Bloque>
            <Bloque destruible="si" nombre="mena">
                <Mineral destruible="si" nombre="diamante" pertecece="mena">
                    Valioso
                </Mineral>
            </Bloque>
            <Agua destruible="no" nombre="agua" pertecece="nube">

            </Agua>
        </Mundo>
    </UnJugador>

    <DosJugadores>
        <Multijugador/>
    </DosJugadores>
    
</Minecraft>
