=== JuanEladio04/LenguajesDeMarcas-DAW/BloqueDTD/ExamenesRepaso/PlanetasDelSistemaSolar.dtd
<!ELEMENT sistemaSolar (Planeta*, Astros+)>
<!ELEMENT Astros ((asteroide | meteorito)?, nebulosa?, cinturon?)>
<!ELEMENT meteorito EMPTY>
<!ELEMENT nebulosa (#PCDATA)>
<!ELEMENT cinturon (#PCDATA)>
<!ELEMENT element-name (#PCDATA)>

<!ELEMENT Planeta (#PCDATA | Satelites | Atmosfera)*>
<!ELEMENT Satelites (#PCDATA)>
<!ATTLIST Satelites planeta IDREF #REQUIRED>
<!ELEMENT Atmosfera (#PCDATA)>
<!ENTITY % color "color (naranja | amarillo | azul | rojo) 'rojo'">
<!ENTITY % caracteristicas " nombre ID #REQUIRED
                    posicion CDATA #IMPLIED
                    habitable (si | no) 'no'
                    habintes CDATA #FIXED 'terricolas' 
                    %color;">
<!ATTLIST Planeta   %caracteristicas;>
<!ATTLIST Satelites %caracteristicas;>

=== JuanEladio04/LenguajesDeMarcas-DAW/BloqueDTD/ExamenesRepaso/PlanetasDelSistemaSolar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar SYSTEM "PlanetasDelSistemaSolar.dtd">

<sistemaSolar>
    <Planeta nombre="Mercurio" habitable="no" color="naranja">
        Priemer planeta
        <Atmosfera>
            oxígeno (42 %), sodio (29 %), hidrógeno (22 %), helio (6 %) y gases traza.
        </Atmosfera>
        <Satelites nombre="ni" planeta="Mercurio">
            No hay satelites
        </Satelites>
    </Planeta>
    <Planeta nombre="Venus" color="rojo" habitable="no">
        <Satelites nombre="no" planeta="Venus">No hay</Satelites>
        <Atmosfera>
            Peligrosa
        </Atmosfera>
        El planeta recibe el nombre debido a la diosa Romana del amor
    </Planeta>
    
    <Astros>
        <meteorito />
        <nebulosa>Grande</nebulosa>
    </Astros>
</sistemaSolar>
